version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - "~/oneaps/docker/postgresql/data:/var/lib/postgresql/data"
    ports:
      - 15432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - "~/oneaps/docker/pgadmin:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.cm
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on: 
      - db
      
  localstack:
    image: localstack/localstack:latest
    restart: always
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
    volumes:
      - "~/oneaps/docker/localstack/data:/tmp/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

  api:
    build: ./api
    environment: 
      - PORT=5001
      - BUCKET_ARN=
      - BUCKET_NAME=
      - LOGGING_BUCKET_NAME=
      - S3_AWS_ACCESS_KEY_ID=
      - S3_AWS_SECRET_ACCESS_KEY=
      - S3_REGION=ap-southeast-2
      - S3_SERVICE_URL=s3://localstack:4566
      - JwtKey=JwtKeyJwtKeyJwtKeyJwtKeyJwtKey
      - JwtIssuer=http://localhost:8000
      - JwtAudience=http://localhost:8000
      - Salt=SecretSecret
      - ENDPOINT_ADDRESS=db
      - DB_PORT=5432
      - DB_NAME=oneaps
      - MASTER_USERNAME=postgres
      - MASTER_PASSWORD=password
    volumes:
      - "./api:/api"
    depends_on: 
      - db

  dbupdate:
    build: ./api
    working_dir: /api/Services.Sql
    environment: 
      - ConnectionString=Host=db;Port=5432;Database=oneaps;Username=postgres;Password=password
    volumes:
      - "./api:/api"
    command: "echo look at readme file for usage"
    depends_on: 
      - db

  client:
    build: ./client
    ports:
      - "8000:8000"
    volumes:
      - "./client:/client"
