version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - "~/oneaps/docker/postgresql/data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 9080:80
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.cm
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on: 
      - db
      
  localstack:
    image: localstack/localstack:latest
    restart: always
    ports:
      - "9566:4566"
      - "9571:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
    volumes:
      - "localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  api:
    build: ./api
    environment: 
      - PORT=5001
      - BUCKET_ARN=
      - BUCKET_NAME=oneaps-bucket-local
      - LOGGING_BUCKET_NAME=
      - S3_AWS_ACCESS_KEY_ID=super
      - S3_AWS_SECRET_ACCESS_KEY=secret
      - S3_REGION=ap-southeast-2
      - S3_SERVICE_URL=http://localstack:4566
      - JwtKey=JwtKeyJwtKeyJwtKeyJwtKeyJwtKey
      - JwtIssuer=http://localhost:9000
      - JwtAudience=http://localhost:9000
      - Salt=SecretSecret
      - ENDPOINT_ADDRESS=db
      - DB_PORT=5432
      - DB_NAME=oneaps
      - MASTER_USERNAME=postgres
      - MASTER_PASSWORD=password
    volumes:
      - "./api:/api"
    depends_on: 
      - db

  dbupdate:
    build: ./api
    working_dir: /api/Services.Sql
    environment: 
      - ConnectionString=Host=db;Port=5432;Database=oneaps;Username=postgres;Password=password
    volumes:
      - "./api:/api"
    command: "echo look at readme file for usage"
    depends_on: 
      - db

  client:
    build: ./client
    ports:
      - "9000:8000"
      - "9002:9002"
    environment: 
      - INTERNAL_STATUS_PORT=9002
    volumes:
      - "./client:/client"

volumes:
  pgadmin:
  localstack: